name: 3 - Test Django Env Vars

on : 
  workflow_dispatch :
    push : 
      branch : 
        - main

jobs: 
  hello:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout the code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install requirements
        run: |
          python -m pip install --upgrade
          python -m pip install -r requirements.txt
      - name: Run tests
        working-directory: ./src
        env:
          DJNAGO_SECRET_KEY: not-good
        run: |
          python manage.py test